### ISSUE TITLE
Can't join meeting on Fedora Silverblue

### ISSUE THREAD

**Issue by Zlopez** [flathub/com.bluejeans.BlueJeans#2] opened 2018-11-14 10:10 UTC
Hi,
I'm using Fedora 29 Silverblue and I have the following issue when joining any meeting - even personal meeting.
![screenshot from 2018-11-14 11-04-29](https://user-images.githubusercontent.com/6943409/48475751-c143fa80-e7fd-11e8-88e5-cc97380724fc.png)

Here is the log made by `flatpak run -v com.bluejeans.BlueJeans`: [bluejeans.log](https://github.com/flathub/com.bluejeans.BlueJeans/files/2580205/bluejeans.log)

**Comment by AsciiWolf** [comment] 2018-11-14 10:58
I was not able to reproduce your issue. Works fine on my Fedora 29 machine. I also tried a clean installation on another machine and it works fine as well. However, I don't have Silverblue here, just regular Fedora and RHEL.

**Comment by AsciiWolf** [comment] 2018-11-14 11:58
I just tested it on Fedora Silverblue 29 and was able to reproduce the issue! However, it works fine on regular Fedora and RHEL. The only suspicious thing from the log is `Rejecting plugin: bjnplugin`. @TingPing Any idea what could be wrong?

edit: Hmm, this one looks suspicious as well: `Could not bind NETLINK socket: Address already in use`

**Comment by AsciiWolf** [comment] 2018-11-14 21:38
I tested it in multiple clean install Silverblue and regular Fedora VMs and it is really happening only on the Silverblue edition of Fedora. I have tried adding the udev shared-module as someone suggested, but it didn't help. I have also tried debugging it using strace, but this is the only relevant thing that I found:
```
) = 1 ([{fd=13, revents=POLLIN}])
read(13, "!", 2)                        = 1
recvmsg(11, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=11, events=POLLIN}, {fd=12, events=POLLIN}, {fd=13, events=POLLIN}], 3, 0) = 0 (Timeout)
recvmsg(11, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=11, events=POLLIN}, {fd=12, events=POLLIN}, {fd=13, events=POLLIN}], 3, 0) = 0 (Timeout)
recvmsg(11, {msg_namelen=0}, 0)         = -1 EAGAIN (Resource temporarily unavailable)
poll([{fd=11, events=POLLIN}, {fd=12, events=POLLIN}, {fd=13, events=POLLIN}], 3, -1[7:1114/193331:INFO:shell_content_browser_plugin.cc(55)] Rejecting plugin: bjnplugin : /var/home/asciiwolf/.config/Blue Jeans/desktop/execdir/package.nw/plugins/npbjnplugin_3.0.6.5.so
```

**Comment by vrutkovs** [comment] 2018-11-14 21:43
Could it be related to `/home` being on `/var/home` in Silverblue?

**Comment by AsciiWolf** [comment] 2018-11-14 21:46
@vrutkovs This shouldn't be a problem.

**Comment by vrutkovs** [comment] 2018-11-14 22:35
Got more info running `flatpak run -v com.bluejeans.BlueJeans --debug-plugin-loading --enable-logging --v=0 --plugin-startup-dialog`
```
Gtk-Message: 23:25:49.689: Failed to load module "canberra-gtk-module"
[74:1114/232549:ERROR:plugin_list.cc(215)] Loading plugin /var/home/vrutkovs/.config/Blue Jeans/desktop/execdir/package.nw/plugins/npbjnplugin_3.0.6.5.so
[74:1114/232549:ERROR:plugin_list_posix.cc(332)] Got info for plugin /var/home/vrutkovs/.config/Blue Jeans/desktop/execdir/package.nw/plugins/npbjnplugin_3.0.6
.5.so Name = "bjnplugin", Description = "", Version = "".
[74:1114/232549:ERROR:plugin_list_posix.cc(562)] Considering /var/home/vrutkovs/.config/Blue Jeans/desktop/execdir/package.nw/plugins/npbjnplugin_3.0.6.5.so (b
jnplugin)
[74:1114/232549:VERBOSE1:plugin_list_posix.cc(585)] Using /var/home/vrutkovs/.config/Blue Jeans/desktop/execdir/package.nw/plugins/npbjnplugin_3.0.6.5.so
[74:1114/232549:ERROR:plugin_list.cc(215)] Loading plugin /var/home/vrutkovs/.config/Blue Jeans/desktop/execdir/package.nw/plugins/skinny_plugin.json
[74:1114/232549:ERROR:plugin_list_posix.cc(269)] Skipping plugin /var/home/vrutkovs/.config/Blue Jeans/desktop/execdir/package.nw/plugins/skinny_plugin.json be
cause it doesn't match the current architecture.
[2:1114/232549:INFO:shell_content_browser_plugin.cc(55)] Rejecting plugin: bjnplugin : /var/home/vrutkovs/.config/Blue Jeans/desktop/execdir/package.nw/plugins
/npbjnplugin_3.0.6.5.so
```

This still does not explain why npbjnplugin_3.0.6.5.so is rejected. Could someone compare the output on Fedora 29?

Since there is no `shell_content_browser_plugin.cc` file in nw.js or Chromium sources I'm guessing this error comes from BJN code - and its rejecting itself :)

**Comment by Zlopez** [comment] 2018-11-15 08:24
@vrutkovs 
The output is the same on Fedora 29 Silverblue.
But I noticed something other at the beginning of the log
```
Pulseaudio user configuration file '/home/zlopez/.config/pulse/client.conf': Error opening file /home/zlopez/.config/pulse/client.conf: No such file or directory
```
Could this mean, that the bluejeans can't read audio configuration? This could explain why the issue is shown when trying to create meeting.

**Comment by AsciiWolf** [comment] 2018-11-15 11:18
@Zlopez The same PulseAudio error is displayed on a regular Fedora as well so this is not an issue.

@vrutkovs Hmm, I see that it is actually using `/var/home`, but there is `The app data path is /home/asciiwolf/.config` previously in the log so this could be a problem after all.

**Comment by AsciiWolf** [comment] 2018-11-15 13:28
I am unfortunately not sure how to change the data path.

**Comment by AsciiWolf** [comment] 2018-11-15 14:52
```
sh-4.4$ echo $HOME
/home/asciiwolf
```

Home directory seems to be correct, but the npbjn plugin is extracted to `/var/home` instead of `/home` by Blue Jeans for some reason.

Seems to be a Flatpak bug to me. @alexlarsson Any idea?

edit: Oops, I am dumb. `/home` is a symlink for `/var/home`. Anyway, the plugin is being loaded from `/var/home` instead of `/home` for some reason.

**Comment by AsciiWolf** [comment] 2018-11-15 15:28
Hmm, it seems that Blue Jeans does not handle the `$XDG_CONFIG_HOME` env variable well and creates a `.config` directory with the plugin directly in `$HOME`. Anyway, this does not seem to be causing the issue on Silverblue.

**Comment by vrutkovs** [comment] 2018-11-16 16:45
@AsciiWolf yep, that's Silverblue specifics. HOME is in fact stored in `/var/home` and being mounted to `/home` on a live system. Flatpak also uses `/home` (but gives access to `/var/home`). It seems Bluejeans doesn't expect that and considers the plugin loaded from `/var/home` as incorrect)

**Comment by AsciiWolf** [comment] 2018-11-16 17:02
@vrutkovs Yeah. The question is why is Blue Jeans loading the plugin from `/var/home` instead of `/home` on Silverblue. (`$HOME` env variable is set to `/home/user`.)

**Comment by AsciiWolf** [comment] 2018-12-02 22:04
I was unfortunately still not able to figure out how to fix this. :-(

**Comment by pnemade** [comment] 2018-12-12 07:45
My observation is on Silverblue29 there is no path exists on my system
`[2:1212/130332:INFO:shell_content_browser_plugin.cc(55)] Rejecting plugin: bjnplugin : /var/home/parag/.config/Blue Jeans/desktop/execdir/package.nw/plugins/npbjnplugin_3.0.6.5.so
`
I found on my Fedora 29, below path exists
`/home/parag/.config/Blue\ Jeans/desktop/execdir`

So I copied directory structure from Fedora 29 to Silverblue 29 and ran this flatpak but then realized plugin is different.  On Fedora 29 its npbjnplugin_2.255.6.5.so whereas in Silverblue 29, its looking for npbjnplugin_3.0.6.5.so

Why both version differed? I used both 29 Fedora releases.

**Comment by AsciiWolf** [comment] 2018-12-12 13:18
Hmm. I have just tried it on both regular Fedora 29 and Fedora Silverblue 29 and the loaded plugin is the same. Anyway, this is not the issue. The issue is that on Silverblue, `/var/home` is created instead of `/home` and `/home` is symlinked to `/var/home` - and Blue Jeans fails when trying to load the plugin from `/var/home`. If I remove the symlinked `/home` and move `/var/home` to `/home`, Blue Jeans works fine on Silverblue. But this change is not persistent and has to be done every time Blue Jeans is started.

I could add this as a workaround to the startup script, but I would rather prefer this being fixed in Flatpak. (I may be wrong, but I don't see any point of creating `/var/home` instead of `/home` inside Flatpaks just because the system `$HOME` is also a symlink to `/var/home`.)

**Comment by vrutkovs** [comment] 2018-12-13 22:27
> If I remove the symlinked /home and move /var/home to /home

This needs to be done in the flatpak, right? I wonder if we should skip sharing xdg-home and create an empty `/home` manually to work this around

**Comment by vrutkovs** [comment] 2018-12-15 18:27
Current workaround: 
* copy desktop file to a different name
* Update `Name=Blue Jeans (Silverblue)`
* Update `Exec=/usr/bin/flatpak run --command=bash com.bluejeans.BlueJeans/x86_64/stable -c "unlink /home && cp /var/home /home -r && bluejeans"`
* Run `update-desktop-database` command

A new app named `Blue Jeans (Silverblue)` would be added and works fine here

**Comment by AsciiWolf** [comment] 2018-12-15 19:24
Thanks, I'll probably add the same workaround to the startup script.

**Closed as completed** 2018-12-15 21:08 UTC
